services:
  postgres:
    container_name: soda-bracket-windmill
    image: postgres:14.18
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
      # .env cannot be dotenvx encrypted.
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/postgres-data
      o: bind
    # This volume is used to persist Postgres data across container restarts.
    # Ensure the host directory exists and has the correct permissions.
    # To set correct ownership, run on your host:
    #   sudo chown -R $(whoami):wheel /var/lib/postgres-data
    #   sudo chmod -R 0755 /var/lib/postgres-data
